### ISSUE TITLE
Request Body (auto generate) not working with nested properties

### ISSUE THREAD

**Issue by zingmane** [nhttp/nhttp_swagger#1]
Swagger doc auto generation is working with simple types like string, number, dateString, etc. but not with `@ValidateNested`. 

The resulting swagger doc with this dto classes is:

```ts
class BrandDto {
  @IsNumber()
  id!: number;

  @IsString()
  displayName!: string;
}

class BatteryCreateDto {
  @ValidateNested()
  @Type(() => BrandDto)
  brand!: BrandDto;

  @IsString()
  displayName!: string;

  @IsNumber()
  capacity!: number;
}
```

![image](https://user-images.githubusercontent.com/148202/222210258-f172091d-06a8-4b04-9b98-5691c0d1c5b8.png)

and example value is:

```json
{
  "brand": "string",
  "displayName": "string",
  "capacity": 0
}
```

Maybe it is also related to <https://github.com/nhttp/nhttp_validator/issues/2>?

btw is there also a possibility to provide more specific examples with auto generate Request Bodies?

**Comment by herudi** [comment]
please read doc => https://github.com/epiphone/class-validator-jsonschema#validatenested-and-arrays. you need custom config if use `class-transformer`.

**Comment by zingmane** [comment]
Thanks again, that was the missing part, it's now working.

I did it this way:

```ts
// index, main, or app.ts
import { defaultMetadataStorage } from "npm:class-transformer@0.5.1/cjs/storage.js"; // workaround for https://github.com/typestack/class-transformer/issues/563
import { validationMetadatasToSchemas } from "npm:class-validator-jsonschema@5.0.0";

const schemas = validationMetadatasToSchemas({
  classTransformerMetadataStorage: defaultMetadataStorage,
  refPointerPrefix: "#/components/schemas/",
});

...

swagger(app, "/api-docs", swaggerDocBuilder.build(), {
  swaggerOptions: {
    ...
  },
  validationMetadatasToSchemas,
  schemas,
});
```

Because of limitations in Typescript's reflection system we have to explicitly define the nested property type in the DTO with `Type`.

```ts
// dto.ts
import { Type } from "npm:class-transformer";

class NestedDto {
  @IsNumber()
  id!: number;

  @IsString()
  name!: string;
}

export class RootDto {
  @IsDefined()
  @ValidateNested()
  @Type(() => NestedDto) // <- explicitly define the nested property type 
  nestedDto!: NestedDto;

  @IsString()
  name!: string;
}
```
